name: Gmail-RDP

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step 2: Clone the chat app server repository
    - name: Clone Chat App Server Repository
      run: |
        git clone https://github.com/Tajbir23/realtime-chat-app-server.git
        cd realtime-chat-app-server

    # Step 3: Install Node.js (Version 20 globally)
    - name: Setup Node.js (v20)
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Step 4: Install dependencies and build project
    - name: Install and Build
      run: |
        cd realtime-chat-app-server  # Ensure we're in the correct directory
        npm install
        npm run build

    # Step 5: Start the Node.js Server and Capture Logs
    - name: Start Node.js Server
      run: |
        cd realtime-chat-app-server  # Ensure we're in the correct directory
        npm start | Tee-Object -FilePath node_server.log
      shell: pwsh

    # Step 6: Show Node.js Server Logs
    - name: Display Node.js Server Logs
      run: |
        Get-Content node_server.log
      shell: pwsh

    # Step 7: Download and Install Playit
    - name: Download and Install Playit
      run: |
        $playitPath = "$env:USERPROFILE\playit.exe"
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile $playitPath
        Start-Sleep -Seconds 5

    # Step 8: Enable Remote Desktop features and configure user
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        $securePassword = ConvertTo-SecureString -AsPlainText "${{ secrets.RDP_PASSWORD }}" -Force
        Set-LocalUser -Name "runneradmin" -Password $securePassword

    # Step 9: Start Playit and Set Up RDP Tunnel
    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait

    # Step 10: Keep the GitHub Action Runner Alive
    - name: Keep the GitHub Action Runner Alive
      run: |
        while ($true) {
          Write-Output "Session is alive - $(Get-Date)"
          Start-Sleep -Seconds 300
        }

    # Step 11: Trigger New Workflow Run (Auto Restart)
    - name: Trigger New Workflow Run
      if: always()
      env:
        REPO_PAT: ${{ secrets.REPO_PAT }}
      run: |
        $payload = @"
        {
          "ref": "main"
        }
        "@

        Invoke-RestMethod `
          -Method POST `
          -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/rdp.yml/dispatches" `
          -Headers @{
            Authorization = "token $env:REPO_PAT"
            Accept = "application/vnd.github.v3+json"
          } `
          -Body $payload
