name: Gmail-RDP

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repository
      uses: actions/checkout@v2

    # Step 2: Install Node.js globally
    - name: Install Node.js globally
      run: |
        # Download Node.js installer
        Invoke-WebRequest -Uri "https://nodejs.org/dist/v20.18.2/node-v20.18.2-x64.msi" -OutFile "nodejs_installer.msi"
        
        # Install Node.js
        Start-Process -FilePath "msiexec.exe" -ArgumentList "/i", "nodejs_installer.msi", "/quiet", "/norestart" -Wait
        
        # Clean up the installer
        Remove-Item "nodejs_installer.msi"

        # Confirm the installation
        node --version
        npm --version

    # Step 3: Clone the repository and install dependencies
    - name: Clone the repository and install dependencies
      run: |
        echo "Cloning the repository..."
        git clone https://github.com/Tajbir23/realtime-chat-app-server.git
        cd realtime-chat-app-server
        
        # List the directory contents to verify the structure
        echo "Listing the directory contents:"
        dir
        
        # Check if package.json exists in the directory
        if (Test-Path "package.json") {
          echo "Found package.json, installing dependencies..."
          npm install
          npm run build
        } else {
          echo "package.json not found in the repository. Exiting!"
          exit 1
        }

    # Step 4: Start the Node.js Server and Capture Logs
    - name: Start Node.js Server
      run: |
        # Ensure we are in the correct directory
        cd realtime-chat-app-server
        npm start | Tee-Object -FilePath node_server.log
      shell: pwsh

    # Step 5: Display Node.js Server Logs
    - name: Display Node.js Server Logs
      run: |
        Get-Content node_server.log
      shell: pwsh

    # Step 6: Download and Install Playit
    - name: Download and Install Playit
      run: |
        $playitPath = "$env:USERPROFILE\playit.exe"
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile $playitPath
        Start-Sleep -Seconds 5

    # Step 7: Enable Remote Desktop features and configure user
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        $securePassword = ConvertTo-SecureString -AsPlainText "${{ secrets.RDP_PASSWORD }}" -Force
        Set-LocalUser -Name "runneradmin" -Password $securePassword

    # Step 8: Start Playit and Set Up RDP Tunnel
    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait

    # Step 9: Keep the GitHub Action Runner Alive
    - name: Keep the GitHub Action Runner Alive
      run: |
        while ($true) {
          Write-Output "Session is alive - $(Get-Date)"
          Start-Sleep -Seconds 300
        }

    # Step 10: Trigger New Workflow Run (Auto Restart)
    - name: Trigger New Workflow Run
      if: always()
      env:
        REPO_PAT: ${{ secrets.REPO_PAT }}
      run: |
        $payload = @"
        {
          "ref": "main"
        }
        "@

        Invoke-RestMethod `
          -Method POST `
          -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/rdp.yml/dispatches" `
          -Headers @{
            Authorization = "token $env:REPO_PAT"
            Accept = "application/vnd.github.v3+json"
          } `
          -Body $payload
