name: Gmail-RDP

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit
      run: |
        # Download the Playit executable
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5

    - name: Enable Remote Desktop Services
      run: |
        # Enable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
        # Set user credentials
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "p@ssw0rd!" -Force)

    - name: Start Playit and Generate New Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        # Remove previous configurations to ensure a new tunnel
        Remove-Item -Path "$env:USERPROFILE\AppData\Local\playit-agent\*" -Recurse -Force -ErrorAction SilentlyContinue
        
        # Start Playit agent with the secret key
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow
        
        # Allow some time for the tunnel to initialize
        Start-Sleep -Seconds 10

    - name: Display the Playit Tunnel Link
      run: |
        # Display Playit logs to identify the new tunnel link
        Get-Content "$env:USERPROFILE\AppData\Local\playit-agent\logs\latest.log" | Select-String -Pattern "public address"

    - name: Keep the GitHub Action Runner Alive
      run: Start-Sleep -Seconds 11800
