name: Gmail-RDP

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    strategy:
      matrix:
        runner:
          - windows-2019
          - windows-2022
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Randomize Windows Runner Version
      id: randomize
      run: |
        $versions = @("windows-2019", "windows-2022")
        $randomVersion = $versions | Get-Random
        echo "runner_version=$randomVersion" >> $env:GITHUB_ENV

    - name: Download and Install Playit
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5  # Give some time for the download to complete
        
    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "p@ssw0rd!" -Force)

    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow
        
    - name: Keep the GitHub Action Runner Alive
      run: |
        Start-Sleep -Seconds 11800  # Adjust the duration based on your needs
